### ISSUE TITLE
Add support for frontend-app-communications

### ISSUE THREAD

**Issue by arbrandes** [overhangio/tutor-mfe#127]
Add official support for [frontend-app-communications](https://github.com/openedx/frontend-app-communications).

#### Tasks

- [x] https://github.com/openedx/frontend-app-communications/pull/125
- [x] https://github.com/openedx/frontend-app-communications/issues/126
- [x] https://github.com/overhangio/tutor-mfe/pull/126
