### ISSUE TITLE
[tutor-mfe] Olive upgrade

### ISSUE THREAD

**Issue by arbrandes** [overhangio/tutor-mfe#67]
We need to do the following to upgrade this to Olive:

* [x] https://github.com/openedx/build-test-release-wg/issues/131
* [x] https://github.com/overhangio/tutor-mfe/pull/65
* [x] https://github.com/openedx/build-test-release-wg/issues/200
* [x] https://github.com/overhangio/tutor-mfe/pull/62
* [x] https://github.com/openedx/frontend-app-course-authoring/issues/383
* [x] https://github.com/openedx/frontend-wg/issues/143
* [x] https://github.com/openedx/frontend-wg/issues/144
* [x] https://github.com/openedx/frontend-app-authn/pull/681
* [x] https://github.com/openedx/frontend-wg/issues/103
* [x] https://github.com/openedx/build-test-release-wg/issues/202
* [x] https://github.com/overhangio/tutor-mfe/pull/69
* [x] https://github.com/openedx/build-test-release-wg/issues/222
* [x] https://github.com/openedx/build-test-release-wg/issues/236
* [x] https://github.com/openedx/build-test-release-wg/issues/235
* [x] https://github.com/overhangio/tutor-mfe/issues/79
* [x] https://github.com/overhangio/tutor-mfe/issues/83
* [x] https://github.com/overhangio/tutor-mfe/pull/66
